### ISSUE TITLE
word w/o a sentence in data formats

### ISSUE THREAD

**Issue by ericamllee** [wolfordj/CS493#1]
http://classes.engr.oregonstate.edu/eecs/perpetual/cs493-400/modules/2-rest-api-use/3-data-formats/ 

![image](https://user-images.githubusercontent.com/24450445/46308557-d414af80-c56e-11e8-817f-1fe67679ffea.png)

The last word in the paragraph should be deleted.

**Comment by wolfordj** [comment]
Closing, will be fixed with next publish. Thanks!
